version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - "$PWD/html:/var/www/html"
    ports:
      - 8080:80
    links:
      - mysql
    env_file: .env

  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
